FROM node:24-bookworm-slim

RUN apt-get update && apt-get install -y bash curl debian-keyring && curl -1sLf \
  'https://artifacts-cli.infisical.com/setup.deb.sh' \
  | bash && apt-get update && apt-get install -y infisical \
  && rm -rf /var/lib/apt/lists/*

RUN corepack enable