
FROM ghcr.io/hsm-sanosoft/hsm-app-be-base:latest

WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod
RUN pnpm dlx puppeteer browsers install chrome
COPY . .

ARG  APP_TYPE
RUN pnpm build:$APP_TYPE
ENV APP_TYPE=${APP_TYPE}
CMD ["sh","-lc","pnpm start:${APP_TYPE}:prod"]
