FROM ghcr.io/hsm-sanosoft/hsm-app-be-base:latest

WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install
RUN pnpm dlx puppeteer browsers install chrome
COPY docker/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r$//' /entrypoint.sh && chmod +x /entrypoint.sh
COPY . .

ENV CHOKIDAR_USEPOLLING=1
ENV CHOKIDAR_INTERVAL=800
ENV WATCHPACK_POLLING=true
ARG APP_TYPE
ENV APP_TYPE=${APP_TYPE}

ENTRYPOINT ["/entrypoint.sh"]
CMD ["sh","-lc","pnpm start:${APP_TYPE}:dev"]
